docker-compose 다운확인

diff --git a/BackEnd/Jenkinsfile b/BackEnd/Jenkinsfile
--- a/BackEnd/Jenkinsfile
+++ b/BackEnd/Jenkinsfile
@@ -17,6 +17,17 @@ pipeline {
                     script {
                         sh "ls -al"
                         sh "chmod +x ./gradlew"
+                        // docker-compose가 설치되어 있는지 확인하고, 없으면 설치
+                        sh '''
+                        if ! command -v docker-compose &> /dev/null
+                        then
+                            echo "docker-compose not found, installing..."
+                            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                            sudo chmod +x /usr/local/bin/docker-compose
+                        else
+                            echo "docker-compose is already installed."
+                        fi
+                        '''
                     }
                 }
             }
